data handicap;
infile 'C:\Users\Brad_2\Desktop\case0601.csv' dlm = ',' firstobs = 2;
input Score Handicap $;
run;
proc print data = handicap;
run;
proc sort data = handicap;
by Handicap;
run;
proc univariate data = handicap;
var Score;
by Handicap;
histogram Score;
qqplot Score;
proc glm data = handicap;
class Handicap;
model Score = Handicap;
means Handicap/lsd  dunnett tukey bon scheffe;
run;
